### ISSUE TITLE
can't get converge result when using AlexNet 

### ISSUE THREAD

**Issue by austingg** [fzliu/style-transfer#19]
hi, @fzliu 
Recently, i am trying using smaller network to generate neural art. However, when use alexnet, it's harder to get converged and get a very blur image. I don't know why. may be alexnet's lrn layer, or big stride in the first layers, or some inproper hyper-parameter

could you share you hyper-parameter used for alexnet, such as learning_rate, style_weight?

Thanks in advance.

**Comment by fzliu** [comment]
(Sorry for the delayed reply, been busy lately.)

Hey there! The results generated from AlexNet unfortunately don't look very nice. If you'd like to stick with AlexNet, I'd recommend 1) fine-tuning a new AlexNet model with all of the LRN layers nixed, and 2) decreasing the number of fully connected layers at the very end. You're free to decrease the stride of the layers, but do note that this will greatly increase your runtime, and you'll have to train the model entirely from scratch.

**Comment by austingg** [comment]
Thanks for your reply.

I have seen the result you generated from AlexNet in you blog. And I know the result should not be as good as VGG or Inception. So you get your result by removing the LRN layers?  I just got terrible result which can't recognize the content image :(

**Comment by fzliu** [comment]
Actually the results you saw were generated without removing LRN layers. If your results are unrecognizable, I'd recommend lowering the style-to-content ratio (maybe to `1e2` or `1e3` as a starting point).

If you paste an image here, I'd be happy to help you debug the problem.

**Comment by austingg** [comment]
Thank you so much.
 I just got similar results as your blog using your code. 
Appreciate your kindly help!
