### ISSUE TITLE
VGG model cannot  run?

### ISSUE THREAD

**Issue by schen119** [fzliu/style-transfer#2]
Hi!
I have successfully run the code and generate the 'result.jpg' by the default googlenet model.
I try to run the VGG 19 by setting the model_name = "vgg" but It just run one 0 iterations generate the result which is identical to content image.
I found the gradient in the data layer is zero. Could you kindly help me to solve the problem?

**Comment by fzliu** [comment]
VGG should be working now, thanks to @dpaiton. Let me know if it's not and I'll take a look at it again.

**Comment by schen119** [comment]
After downloading the new version form @dpaiton, it works!
Thank you!
