### ISSUE TITLE
shapeless blob?

### ISSUE THREAD

**Issue by zzkt** [fzliu/style-transfer#24]
Any idea what is going on with this?

style.py:main:14:09:25.062 -- Starting style transfer.
style.py:main:14:09:25.062 -- Running net on CPU.
style.py:main:14:09:26.432 -- Successfully loaded images.
style.py:main:14:09:29.054 -- Successfully loaded model vgg16.
Traceback (most recent call last):
  File "style.py", line 520, in <module>
    main(args)
  File "style.py", line 499, in main
    n_iter=args.num_iters, verbose=args.verbose)
  File "style.py", line 401, in transfer_style
    orig_dim = min(self.net.blobs["data"].shape[2:])
AttributeError: 'Blob' object has no attribute 'shape'

**Comment by fzliu** [comment]
Try replacing that line with `orig_dim = min(self.net.blobs["data"].data.shape[2:])`.

**Comment by zzkt** [comment]
thanks. that does the trick.

**Comment by frischzenger** [comment]
i have the same error from this code, with orig_dim = min(self.net.blobs["data"].data.shape[2:]) replaced, the problem still exist

**Comment by fzliu** [comment]
Try updating Caffe to master - it should work then.

**Comment by enzyme69** [comment]
@fzliu can we have a working version of Caffe included with the style-transfer-master? so far, using Windows 7, 64 bit and Python 27, I only manage to get it working with GPU when using GitHub repository: deepdream-windows-cuda_v75_nocudnn and DeepDreamAnim-master.

updating Caffe is apparently requires compile. not simply pip install caffe --upgrade...
