### ISSUE TITLE
Where to get the 'stylenet' model?

### ISSUE THREAD

**Issue by waltner** [fzliu/style-transfer#29]
Hi, 

in the models folder there is 'stylenet', however it cannot be automatically downloaded (as not included in the download script). Which model is this, can you provide a link so I can fetch it?

€: I would also need the related weights as defined in lines 59-85 for the other models.

Thanks in advance, Georg.

**Comment by fzliu** [comment]
That was primarily for debugging & testing purposes, especially since VGG can be expensive to run.
