### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'outputs/sanfrancisco-starry_night-vgg19-content-1e4-512.jpg'

### ISSUE THREAD

**Issue by tnikolla** [fzliu/style-transfer#31]
Hi,

it seems that I have problems with writing the output image. Here is a copy from my terminal.

`iki@iki-CELSIUS-R570-2:~/artistic_style/style-transfer$ python style.py -s ./images/style/starry_night.jpg -c ./images/content/sanfrancisco.jpg -m vgg19 -g 0style.py:main:21:04:09.368 -- Starting style transfer.
style.py:main:21:04:09.650 -- Running net on GPU 0.
style.py:main:21:04:09.699 -- Successfully loaded images.
style.py:main:21:04:13.625 -- Successfully loaded model vgg19.
Optimizing: 100% ||||||||||||||||||||||||||||||||||||||||||||||||| Time: 0:14:26
style.py:main:21:18:41.323 -- Ran 513 iterations in 868s.
/home/iki/.local/lib/python2.7/site-packages/skimage/util/dtype.py:110: UserWarning: Possible precision loss when converting from float32 to uint8
  "%s to %s" % (dtypeobj_in, dtypeobj))
Traceback (most recent call last):
  File "style.py", line 520, in <module>
    main(args)
  File "style.py", line 514, in main
    imsave(out_path, img_as_ubyte(img_out))
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 168, in imsave
    im.save(name)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1676, in save
    fp = builtins.open(fp, "wb")
IOError: [Errno 2] No such file or directory: 'outputs/sanfrancisco-starry_night-vgg19-content-1e4-512.jpg'
`

Thank you for the implementation!

Tomi

**Comment by tnikolla** [comment]
I tried also to put the output folder
`python style.py -s ./images/style/starry_night.jpg -c ./images/content/sanfrancisco.jpg -m vgg19 -g 0 -o images/results/`

and now I get this error on the terminal
`style.py:main:13:20:48.008 -- Starting style transfer.
style.py:main:13:20:48.291 -- Running net on GPU 0.
style.py:main:13:20:48.340 -- Successfully loaded images.
iki@iki-CELSIUS-R570-2:~/artistic_style/style-transfer$ python style.py -s ./images/style/starry_night.jpg -c ./images/content/sanfrancisco.jpg -m vgg19 -g 0 -o images/results/
style.py:main:13:28:09.431 -- Starting style transfer.
style.py:main:13:28:09.715 -- Running net on GPU 0.
style.py:main:13:28:09.764 -- Successfully loaded images.
style.py:main:13:28:30.732 -- Successfully loaded model vgg19.
Optimizing: 100% ||||||||||||||||||||||||||||||||||||||||||||||||| Time: 0:14:54
style.py:main:13:43:25.934 -- Ran 513 iterations in 895s.
/home/iki/.local/lib/python2.7/site-packages/skimage/util/dtype.py:110: UserWarning: Possible precision loss when converting from float32 to uint8
  "%s to %s" % (dtypeobj_in, dtypeobj))
Traceback (most recent call last):
  File "style.py", line 520, in <module>
    main(args)
  File "style.py", line 514, in main
    imsave(out_path, img_as_ubyte(img_out))
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 168, in imsave
    im.save(name)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1667, in save
    raise KeyError(ext)  # unknown extension
KeyError: ''
`

Thanks for any advice or ideas!

Tomi

**Comment by Haalon** [comment]
you need to name your output file too, choosing only folder isnt enogh. 
example (i have all images at the same directory)
`python style.py -s mosaiq.jpg -c orin.jpg -m vgg19 -r 50000  -o 0output.jpg -n 900  -l 900`

**Comment by fzliu** [comment]
Hey there, and sorry for the delay! Make sure the directory you specify exists, and that you're providing the full filename, otherwise it won't work.

**Comment by tnikolla** [comment]
Thanks a lot! Everything works smooth.
And sorry for the delay and this type of question but I was frustrated with setting up the correct Ubuntu version, GPU drivers and tools, python packages and so on.
