### ISSUE TITLE
'Blob' object has no attribute 'shape'

### ISSUE THREAD

**Issue by lshamis** [fzliu/style-transfer#4]
On line 148 [[ x.reshape(net.blobs["data"].shape[1:]) ]]
net.blobs["data"] is a Blob object, which doesn't seem to have a shape field.

I think it's supposed to be [[ x.reshape(net.blobs["data"].data.shape[1:]) ]]

**Comment by fzliu** [comment]
`net.blobs["data"].shape` actually exists as a `caffe.IntVec` object in the latest version of Caffe, which is automatically cast as tuple in the `np.ndarray.reshape` function. What version of Caffe are you using? I'm happy to make this change if it provides some backwards compatibility.

**Comment by lshamis** [comment]
Not sure how to check Caffe version.  Just rebuilt the newest version and net.blobs["data"].shape works.
Thanks!

(Did they really add that in the last 1-2 weeks?)
