### ISSUE TITLE
I can't continue after load image!

### ISSUE THREAD

**Issue by YangJuYoung** [fzliu/style-transfer#41]
<img width="492" alt="2016-07-14 5 03 31" src="https://cloud.githubusercontent.com/assets/20446264/16818036/a235536e-4980-11e6-9e6a-080850290caa.png">
Please help me T.T

**Comment by fzliu** [comment]
Make sure to download the models first before running the code.

**Comment by YangJuYoung** [comment]
Thank you! I solve that problem, but now I have another problem in save image.
Could you help me one more time? T_T
<img width="492" alt="2016-07-15 10 28 47" src="https://cloud.githubusercontent.com/assets/20446264/16875706/c3bf5fb4-4adb-11e6-8b84-f74f77b97e1f.png">

**Comment by fzliu** [comment]
Specify a whole path, e.g. `images/results/result.jpg` instead of just `images/results`.

**Comment by YangJuYoung** [comment]
I really appreciate your help!:)
